### ISSUE TITLE
does not maintain ?next GET data

### ISSUE THREAD

**Issue by CDWimmer** [ToxicFrazzles/Django-Oauth-Login#1]
Often, e.g. when using LoginRequiredMixin, you'll get some data magically tagged onto the URL after you've been sent to the login page that for a more usual login would send you to that remembered URL. It would be very helpful if it were possible maintain that redirect information after going through oauth.

**Comment by ToxicFrazzles** [comment]
Do you have the name of this magical query parameter?

**Comment by ToxicFrazzles** [comment]
Oh wait I'm dumb and didn't see it in the title. "next" is the parameter.

**Comment by ToxicFrazzles** [comment]
Multilogin does handle the "next" parameter, however it only handles it when one of the login method pages receives it. I imagine you have an intermediate login page where you can select the login method and this page is not passing the "next" parameter to multilogin.
